### ISSUE TITLE
New version of Nodejs

### ISSUE THREAD

**Issue by basickarl** [ramr/nodejs-custom-version-openshift#9]
https://nodejs.org/

Current Version: v0.12.2

**Comment by ramr** [comment]
Fixed - updated docs as well.   Just as an aside, don't really need the version bumped - its good to have, yeah. But you can do that yourself by just running:  
``` echo 0.12.2 >> .openshift/markers/NODEJS_VERSION ```  before you ``` git push ```  to your OpenShift app.
